threads:
  multiplier: 8

generator:
  users_url: https://randomuser.me/api/?nat=gb&results=1&exc=picture,registered,id,phone,cell,nat
  ratings_file: data/ml-latest-small/ratings.csv
  movies_file: data/ml-latest-small/movies.csv

ledger:
  endpoint: grpc://localhost:3999

ods:
  endpoint: mongodb://localhost:27017/
  database: movie_ratings
